c_compiler_version:
  - 10
cxx_compiler_version:
  - 10
cuda_compiler_version:
  - 11.8
fortran_compiler_version:
  - 10
cudnn:
  - 8
cdt_name:
  - cos7
docker_image:
  - quay.io/condaforge/linux-anvil-cuda:11.8           # [linux64 and cuda_compiler_version != "None"]
  - quay.io/condaforge/linux-anvil-ppc64le-cuda:11.8   # [linux and ppc64le and cuda_compiler_version != "None"]
  - quay.io/condaforge/linux-anvil-aarch64-cuda:11.8   # [linux and aarch64 and cuda_compiler_version != "None"]
